# Generated by Django 4.2.28 on 2026-02-17 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_initial"),
        ("registry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="area",
            field=models.ForeignKey(
                blank=True,
                help_text="The geographic area this post represents (e.g., a specific constituency).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="geo.geographicarea",
                verbose_name="Geographic Area",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="organization",
            field=models.ForeignKey(
                help_text="The organization the person belongsto (e.g., The Parliament).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="registry.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="post",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific post held (e.g., 'MP for Lagos West').Optional if generic membership.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="memberships",
                to="registry.post",
                verbose_name="Post",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="selection_method",
            field=models.CharField(
                choices=[
                    ("elected", "Elected"),
                    ("appointed", "Appointed"),
                    ("ex_officio", "Ex Officio"),
                    ("hereditary", "Hereditary"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                help_text="How the person obtained this position(e.g., elected vs appointed).",
                max_length=50,
                verbose_name="Selection Method",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization that contains this one(e.g., a committee within a parliament).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="registry.organization",
                verbose_name="Parent Organization",
            ),
        ),
    ]
