# Generated by Django 4.2.28 on 2026-02-17 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0002_post_area_alter_membership_organization_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "ordering": ["country_code", "name"],
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="chamber_type",
            field=models.CharField(
                choices=[
                    ("unicameral", "Unicameral"),
                    ("lower_chamber", "Lower Chamber"),
                    ("upper_chamber", "Upper Chamber"),
                    ("none", "Non-Legislative"),
                ],
                default="none",
                help_text="If this is a legislature, specify the type of chamber.",
                max_length=20,
                verbose_name="Chamber Type",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization that contains this one (e.g., a committee within a parliament).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="registry.organization",
                verbose_name="Parent Organization",
            ),
        ),
    ]
