# Generated by Django 4.2.28 on 2026-02-17 16:42

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeographicArea",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "country_code",
                    models.CharField(
                        help_text="ISO-3166-1 alpha-3 code (e.g., NGA, KEN)",
                        max_length=3,
                        verbose_name="Country Code",
                    ),
                ),
                (
                    "admin_level",
                    models.CharField(
                        choices=[
                            ("country", "Country"),
                            ("state", "State/Province"),
                            ("district", "District"),
                            ("constituency", "Constituency"),
                        ],
                        default="country",
                        max_length=20,
                        verbose_name="Administrative Level",
                    ),
                ),
                (
                    "continent_region",
                    models.CharField(
                        choices=[
                            ("north", "North Africa"),
                            ("west", "West Africa"),
                            ("east", "East Africa"),
                            ("central", "Central Africa"),
                            ("southern", "Southern Africa"),
                        ],
                        max_length=20,
                        verbose_name="Continent Region",
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True,
                        help_text="Spatial boundaries or point location for this area",
                        null=True,
                        srid=4326,
                        verbose_name="Geometry",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="The larger area containing this one (e.g., a State containing a District)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="geo.geographicarea",
                    ),
                ),
            ],
            options={
                "verbose_name": "Geographic Area",
                "verbose_name_plural": "Geographic Areas",
                "ordering": ["country_code", "admin_level", "name"],
            },
        ),
    ]
